### ISSUE TITLE
TypeError: audioconcat(...).output is not a function

### ISSUE THREAD

**Issue by qawemlilo** [h2non/audioconcat#3]
Hi @h2non , the example in the docs seems to contain errors.

``` javascript
var videoshow = require('audioconcat')

var songs = [
  'beatles.mp3',
  'greenday.mp3',
  'u2.mp3'
]

audioconcat(songs)
  .output('all.mp3')
  .on('start', function (command) {
    console.log('ffmpeg process started:', command)
  })
  .on('error', function (err, stdout, stderr) {
    console.error('Error:', err)
    console.error('ffmpeg stderr:', stderr)
  })
  .on('end', function (output) {
    console.error('Audio created in:', output)
  });
```
1. `audioconcat` is undefined - I think this is just a typo on the first line.
2. the method `output` is not available, when I took a look at the code I noticed that the `output` is checked for in the options.

**Comment by qawemlilo** [comment]
The example doesn't seem to be working at all - I'm trying out v0.1.2.

**Comment by h2non** [comment]
Fixed. Take a look and try it again.

**Comment by qawemlilo** [comment]
Thanks, working fine now.

**Comment by attilavago** [comment]
This is still not fixed. And why am I calling audioconcat in a videoshow variable?!?

LE: @h2non  found the issue. [Here](https://www.npmjs.com/package/audioconcat#api) you still have the old code. You might want to update that. :)

**Comment by algendy** [comment]
Hey guys, still getting TypeError: audioconcat(...).output is not a function, any workaround for it?
